import type { PostType } from '@/lib/types/post';

export interface TemplateField {
  name: string;
  label: string;
  type: 'text' | 'textarea' | 'select' | 'tags' | 'url' | 'checkbox' | 'country';
  required?: boolean;
  options?: string[];
  placeholder?: string;
}

export const POST_TEMPLATES: Record<PostType, TemplateField[]> = {
  job: [
    { name: 'title', label: 'Job Title', type: 'text', required: true },
    { name: 'organization', label: 'Company', type: 'text', required: true },
    { name: 'country', label: 'Country', type: 'country', required: true },
    { name: 'location', label: 'Location', type: 'text', required: true },
    { name: 'workType', label: 'Work Type', type: 'select', options: ['Full Time', 'Part Time', 'Contract', 'Remote', 'Hybrid'] },
    { name: 'compensation', label: 'Salary', type: 'text', placeholder: 'e.g. $80-100k or ₹8-12 LPA' },
    { name: 'description', label: 'Description', type: 'textarea', required: true },
    { name: 'skills', label: 'Skills', type: 'tags' },
    { name: 'requirements', label: 'Requirements', type: 'tags' },
    { name: 'applyUrl', label: 'Apply URL', type: 'url' },
    { name: 'logo', label: 'Logo Emoji', type: 'text', placeholder: '💼' },
    { name: 'deadline', label: 'Application Deadline', type: 'text' },
    { name: 'featured', label: 'Featured', type: 'checkbox' },
  ],
  internship: [
    { name: 'title', label: 'Internship Title', type: 'text', required: true },
    { name: 'organization', label: 'Company', type: 'text', required: true },
    { name: 'country', label: 'Country', type: 'country', required: true },
    { name: 'location', label: 'Location', type: 'text', required: true },
    { name: 'workType', label: 'Type', type: 'select', options: ['Full Time', 'Part Time', 'Remote', 'Hybrid'] },
    { name: 'compensation', label: 'Stipend', type: 'text', placeholder: 'e.g. ₹15-20K/month' },
    { name: 'description', label: 'Description', type: 'textarea', required: true },
    { name: 'skills', label: 'Skills', type: 'tags' },
    { name: 'requirements', label: 'Requirements', type: 'tags' },
    { name: 'applyUrl', label: 'Apply URL', type: 'url' },
    { name: 'logo', label: 'Logo Emoji', type: 'text' },
    { name: 'deadline', label: 'Deadline', type: 'text' },
    { name: 'featured', label: 'Featured', type: 'checkbox' },
  ],
  scholarship: [
    { name: 'title', label: 'Scholarship Title', type: 'text', required: true },
    { name: 'organization', label: 'Provider', type: 'text', required: true },
    { name: 'country', label: 'Country', type: 'country', required: true },
    { name: 'location', label: 'Location', type: 'text', required: true },
    { name: 'amount', label: 'Award Amount', type: 'text', required: true },
    { name: 'description', label: 'Description', type: 'textarea', required: true },
    { name: 'skills', label: 'Fields of Study', type: 'tags' },
    { name: 'eligibility', label: 'Eligibility', type: 'tags' },
    { name: 'applyUrl', label: 'Apply URL', type: 'url' },
    { name: 'deadline', label: 'Deadline', type: 'text', required: true },
    { name: 'featured', label: 'Featured', type: 'checkbox' },
  ],
  'govt-job': [
    { name: 'title', label: 'Job Title', type: 'text', required: true },
    { name: 'organization', label: 'Agency/Department', type: 'text', required: true },
    { name: 'country', label: 'Country', type: 'country', required: true },
    { name: 'location', label: 'Location', type: 'text', required: true },
    { name: 'workType', label: 'Type', type: 'select', options: ['Full Time', 'Contract', 'Temporary'] },
    { name: 'compensation', label: 'Salary Grade', type: 'text' },
    { name: 'description', label: 'Description', type: 'textarea', required: true },
    { name: 'skills', label: 'Required Skills', type: 'tags' },
    { name: 'requirements', label: 'Requirements', type: 'tags' },
    { name: 'applyUrl', label: 'Apply URL', type: 'url' },
    { name: 'deadline', label: 'Application Deadline', type: 'text' },
    { name: 'featured', label: 'Featured', type: 'checkbox' },
  ],
  competition: [
    { name: 'title', label: 'Competition Title', type: 'text', required: true },
    { name: 'organization', label: 'Organizer', type: 'text', required: true },
    { name: 'country', label: 'Country', type: 'country', required: true },
    { name: 'location', label: 'Location', type: 'text', required: true },
    { name: 'fee', label: 'Entry Fee', type: 'text', placeholder: 'Free or amount' },
    { name: 'compensation', label: 'Prize Pool', type: 'text' },
    { name: 'description', label: 'Description', type: 'textarea', required: true },
    { name: 'tags', label: 'Categories', type: 'tags' },
    { name: 'applyUrl', label: 'Register URL', type: 'url' },
    { name: 'deadline', label: 'Registration Deadline', type: 'text' },
    { name: 'featured', label: 'Featured', type: 'checkbox' },
  ],
  'mock-test': [
    { name: 'title', label: 'Test Name', type: 'text', required: true },
    { name: 'organization', label: 'Provider', type: 'text', required: true },
    { name: 'country', label: 'Country', type: 'country', required: true },
    { name: 'location', label: 'Mode', type: 'text', placeholder: 'Online' },
    { name: 'description', label: 'Description', type: 'textarea', required: true },
    { name: 'skills', label: 'Topics Covered', type: 'tags' },
    { name: 'applyUrl', label: 'Start URL', type: 'url' },
    { name: 'featured', label: 'Featured', type: 'checkbox' },
  ],
  'mock-interview': [
    { name: 'title', label: 'Interview Role', type: 'text', required: true },
    { name: 'organization', label: 'Provider', type: 'text', required: true },
    { name: 'country', label: 'Country', type: 'country', required: true },
    { name: 'location', label: 'Mode', type: 'text', placeholder: 'Online' },
    { name: 'description', label: 'Description', type: 'textarea', required: true },
    { name: 'skills', label: 'Skills Assessed', type: 'tags' },
    { name: 'applyUrl', label: 'Start URL', type: 'url' },
    { name: 'featured', label: 'Featured', type: 'checkbox' },
  ],
  mentorship: [
    { name: 'title', label: 'Mentorship Title', type: 'text', required: true },
    { name: 'organization', label: 'Mentor/Platform', type: 'text', required: true },
    { name: 'country', label: 'Country', type: 'country', required: true },
    { name: 'location', label: 'Mode', type: 'text', placeholder: 'Online' },
    { name: 'compensation', label: 'Price per Session', type: 'text' },
    { name: 'description', label: 'Description', type: 'textarea', required: true },
    { name: 'skills', label: 'Expertise Areas', type: 'tags' },
    { name: 'applyUrl', label: 'Book URL', type: 'url' },
    { name: 'featured', label: 'Featured', type: 'checkbox' },
  ],
  'prep-resource': [
    { name: 'title', label: 'Resource Title', type: 'text', required: true },
    { name: 'organization', label: 'Provider', type: 'text', required: true },
    { name: 'country', label: 'Country', type: 'country', required: true },
    { name: 'location', label: 'Format', type: 'text', placeholder: 'Online / Self-paced' },
    { name: 'description', label: 'Description', type: 'textarea', required: true },
    { name: 'tags', label: 'Categories', type: 'tags' },
    { name: 'applyUrl', label: 'Access URL', type: 'url' },
    { name: 'featured', label: 'Featured', type: 'checkbox' },
  ],
};

export function getDefaultPostValues(type: PostType): Record<string, unknown> {
  return {
    type,
    status: 'draft',
    country: 'IN',
    locale: 'en-IN',
    location: '',
    workType: 'Full Time',
    skills: [],
    tags: [],
    requirements: [],
    responsibilities: [],
    benefits: [],
    eligibility: [],
    applicationProcess: [],
    logo: '💼',
    featured: false,
    description: '',
    organization: '',
    title: '',
  };
}
